// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: athlete_split.sql

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateAthleteSplitsParams struct {
	RaceID    uuid.UUID
	EventID   uuid.UUID
	SplitID   uuid.UUID
	AthleteID uuid.UUID
	Tod       pgtype.Timestamp
	GunTime   pgtype.Interval
	NetTime   pgtype.Interval
}
